import mongoose from "mongoose";

const userSchema = new mongoose.Schema(
  {
    username: {
      type: String,
      required: true,
      unique: true,
      trim: true,
    },
    email: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
    },
    password: {
      type: String,
      required: true,
    },
    avatar: {
      type: String,
      default: "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_900.png",
    },
    
    // 🏫 SCHOOL PRIDE & REP
    school: { 
      type: String, 
      default: "", 
      trim: true 
    },
    
    // ✅ VERIFICATION STATUS
    verified: {
      type: Boolean,
      default: false,
    },
    subscriptionExpiry: { 
  type: Date, 
  default: null 
},
    
    // 🛡️ PERMISSIONS
    role: {
      type: String,
      enum: ["artist", "admin", "superadmin"],
      default: "artist",
      required: true
    },

    // ⚡ SOCIAL ENGINE (Who is in your Hype-Squad?)
    followers: [
      { 
        type: mongoose.Schema.Types.ObjectId, 
        ref: "User" 
      }
    ],
    following: [
      { 
        type: mongoose.Schema.Types.ObjectId, 
        ref: "User" 
      }
    ],


 

  // ... all your existing code (username, school, followers, stats, etc.)

 
    totalHypes: { 
      type: Number, 
      default: 0 
    }, // Total Likes across all their work
    arenaRank: { 
      type: Number, 
      default: 0 
    }, // Current national ranking
    bio: { 
      type: String, 
      maxlength: 150, 
      default: "Yenuvia Masterpiece Creator " 
    },

    // 💸 MONETIZATION & MOMO SETTINGS (Paystack Subaccount Integration)
    momoName: { 
      type: String, 
      trim: true,
      default: "" 
      // The official registered name on the Momo account
    },
    momoNumber: { 
      type: String, 
      trim: true,
      default: "" 
    },
    momoNetwork: { 
      type: String, 
      enum: ["MTN", "VOD", "ATL", ""], // MTN, Vodafone/Telecel, AirtelTigo
      default: "" 
    },
    paystackSubaccountCode: { 
      type: String, 
      default: "" 
      // This is the ACCT_xxx code generated by Paystack
    },
    ghanaCardVerified: { type: Boolean, default: false },
  ghanaCardNumber: { type: String, default: "" },
  },
  { timestamps: true }
);

// Add an index to username for lightning-fast profile searches
userSchema.index({ username: 1 });

const User = mongoose.model("User", userSchema);
export default User;